In [1]:
import tensorflow as tf 
print(tf.__version__)

/Users/phanirajendra/.pyenv/versions/3.11.9/lib/python3.11/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


2.16.2


In [ ]:
[2.20.x]

In [ ]:
# Datatypes in TF
[ int, float , bool, string , complex ] = 1nt8, int 16, int 32, int 64 / float 

tf.int8, tf.int16, tf.int32, tf.int64
tf.float16, tf.float32, tf.float64
tf.string 
tf.bool
tf.qint8, tf.qint16, 32, -> Quantized 


In [3]:
a = tf.constant(10)
print(a)
type(a)

tf.Tensor(10, shape=(), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [4]:
b = tf.Variable(20)
print(b)
type(b)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
import numpy as np

In [6]:
aa = np.array(10)
print(aa)
type(aa)

10


numpy.ndarray

In [ ]:
# Scaler = 0
# Vector = 1
# Matrix = 2
# Tensor = 3


In [ ]:
# converting an array into a tensor 

In [8]:
cv = np.arange(12).reshape(3,4)
print(cv)

print(cv.ndim)
type(cv)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


numpy.ndarray

In [ ]:
# Converting an array into a tensor / creating a tensor with an array 
cv.convert to an tensor( destination) = > type casting 

a.

In [10]:
# All of tensor operations 

one_dim_tens = tf.constant([1,2,3,4,5])
second_one_dim_tens = tf.constant([6, 7, 8, 9, 10])

In [12]:
one_dim_array = np.array([1, 2, 3, 4, 5])
second_dim_array = np.array([6, 7, 8, 9, 10])
result_array_add = np.add(one_dim_array, second_dim_array)
result_array_sub = np.subtract(one_dim_array, second_dim_array)
result_array_mul = np.multiply(one_dim_array, second_dim_array)
result_array_div = np.divide(one_dim_array, second_dim_array)
print(result_array_add, result_array_sub, result_array_mul, result_array_div)

[ 7  9 11 13 15] [-5 -5 -5 -5 -5] [ 6 14 24 36 50] [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [11]:
result_add = tf.add(one_dim_tens, second_one_dim_tens)
result_mul = tf.multiply(one_dim_tens, second_one_dim_tens)
result_sub = tf.subtract(one_dim_tens, second_one_dim_tens)
result_div = tf.divide(one_dim_tens, second_one_dim_tens)

print(result_add)
print(result_mul)
print(result_sub)
print(result_div)



tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([ 6 14 24 36 50], shape=(5,), dtype=int32)
tf.Tensor([-5 -5 -5 -5 -5], shape=(5,), dtype=int32)
tf.Tensor([0.16666667 0.28571429 0.375      0.44444444 0.5       ], shape=(5,), dtype=float64)


In [13]:
nn = tf.convert_to_tensor(one_dim_array, dtype=tf.float32)
type(nn)

tensorflow.python.framework.ops.EagerTensor

In [16]:
# performing a matrix mul in numpy 
s_mat_1 = np.arange(12).reshape(3, 4)
s_mat_2 = np.arange(12,24).reshape(4, 3)
mat_mul_np = np.matmul(s_mat_1, s_mat_2)
print(mat_mul_np)


[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [17]:
s_mat_1 @ s_mat_2

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [18]:
# performing a matrix multiplication using tensorflow 

# converting an array into tensor 
t_mat_1 = tf.convert_to_tensor(s_mat_1, dtype=tf.float32)
t_mat_2 = tf.convert_to_tensor(s_mat_2, dtype=tf.float32)
t_mat_1 @ t_mat_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[114., 120., 126.],
       [378., 400., 422.],
       [642., 680., 718.]], dtype=float32)>

In [19]:
# Performing a dot product in numpy 
array_dot_p = np.dot(one_dim_array, second_dim_array)
print(array_dot_p)

130


In [20]:
# performing dot product using tensorfow 
tens_dot_p = tf.tensordot(one_dim_tens, second_one_dim_tens, axes=1)
print(tens_dot_p)


tf.Tensor(130, shape=(), dtype=int32)


In [21]:
# to install pytorch 

! pip install -qU  torch 

In [22]:
# Finding verioin of pytorch 
import torch


In [23]:
torch.__version__

'2.9.1'

In [24]:
# Creating a variable using pytorch  , tensor 
mm = torch.tensor([1, 2, 3, 4, 5])
xx = torch.tensor([6, 7, 8, 9, 10])


In [26]:
# now performing math ops using pytorch 

result_torch_add = torch.add(mm, xx)
result_torch_sub = torch.sub(mm, xx)
result_torch_mul = torch.mul(mm, xx)
result_torch_div = torch.div(mm, xx)
print(result_torch_add, result_torch_sub, result_torch_mul, result_torch_div)


tensor([ 7,  9, 11, 13, 15]) tensor([-5, -5, -5, -5, -5]) tensor([ 6, 14, 24, 36, 50]) tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])


In [28]:
# performing dot product using pytorch 

print(np.dot(s_mat_1, s_mat_2))
print(tf.tensordot(one_dim_tens, second_one_dim_tens, axes=1))
print(torch.dot(mm, xx))

[[114 120 126]
 [378 400 422]
 [642 680 718]]
tf.Tensor(130, shape=(), dtype=int32)
tensor(130)
