In [1]:
print('Hi')

Hi


In [ ]:
# Working with some of the function of Numpy 

In [4]:
! pip install -qU pandas numpy matplotlib seaborn scikit-learn

In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn 

In [7]:
a1 = np.random.random((3,3))
a1 = np.round(a1 * 100)
print(a1)

[[23. 75. 23.]
 [93. 36. 49.]
 [75. 10. 41.]]


In [8]:
# MAX and MIN functions
print(np.max(a1))

93.0


In [9]:
print(np.min(a1))

10.0


In [10]:
# Performing sum of a1
print(np.sum(a1))

425.0


In [11]:
# finding the shape of a1
print(a1.shape)
print(a1.ndim)

(3, 3)
2


In [12]:
# printing a1 
print(a1)

[[23. 75. 23.]
 [93. 36. 49.]
 [75. 10. 41.]]


In [13]:
# finding the sum of a1
print(np.sum(a1))

425.0


In [ ]:
# finding max value row wise 
print(np.max(a1, axis=0)) # Axis 0 -> row wise,  Axis 1 -> column wise


[93. 75. 49.]


In [15]:
# findint the max value column wise
print(np.max(a1, axis=1))

[75. 93. 75.]


In [16]:
print(a1)

[[23. 75. 23.]
 [93. 36. 49.]
 [75. 10. 41.]]


In [19]:
a1[2]

array([75., 10., 41.])

In [22]:
print(np.max(a1[2]))

75.0


In [23]:
# finding mean value of a1 
print(np.mean(a1))

47.22222222222222


In [24]:
# finding mean value axis wise 
print(np.mean(a1, axis=0))

[63.66666667 40.33333333 37.66666667]


In [31]:
291 / 3

97.0

In [32]:
# printing a1 
print(a1)

[[23. 75. 23.]
 [93. 36. 49.]
 [75. 10. 41.]]


In [ ]:
# Mean = it is an average column 
# Median = may be the middle number 
# Mode = most repeating number 

In [ ]:
# finding the mean value of a1
print(np.median(a1, axis=1))

[40.33333333 59.33333333 42.        ]


In [36]:
# finding the median value of a1
print(np.median(a1, axis=0))

[75. 36. 41.]


In [37]:
# finding the mode value of a1
print(np.mean(a1, axis=0))

[63.66666667 40.33333333 37.66666667]


In [ ]:
#  finding std [ standard deviation of a1]
# Define std : Standard Deviation in Statistics is a measure of the amount of variation or dispersion of a set of values.
# A low standard deviation indicates that the values tend to be close to the mean of the set, while a high standard deviation indicates that the values are spread out over a wider range.
# Standard Deviation = sqrt( (sum of (x - mean) ^ 2) / n )
# Standard Deviation = sqrt( (sum of (x - mean) ^ 2) / n )
# Define Mean : Mean is the average of the numbers.
# Mean = (sum of all numbers) / (total numbers)
# Define : Mode :- Mode. in stats refers to 
print(np.std(a1, axis=1))
print(np.std(a1, axis=0))
print(np.std(a1))

26.594810595627184


In [39]:
b1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  

In [41]:
# Finding stats information from b1
# mean =  Mean = (sum of all numbers) / (count of  numbers)
(1+2+3+4+5+6+7+8+9+10) / 10

5.5

In [47]:
#  Finding medin value of b1
#  Define Median : Median is the middle value of a set of numbers.
#   To find middle value , we need to know if there even numbers or odd numbers 
#print(np.median(b1))

c_median = [1, 2, 3, 4,   5,    6, 7, 8, 9 ]

print(np.median(c_median))


5.0


In [49]:
# Finding the mode value 
print(np.mode(b1))

AttributeError: module 'numpy' has no attribute 'mode'

In [ ]:
# Standard Deviation : Standard Deviation is a measure of how spread out numbers are.
# Standard Deviation = sqrt( (sum of (x - mean) ^ 2) / n )
# Standard Deviation = sqrt( (sum of (x - mean) ^ 2) / n )
print(np.std(b1))

In [ ]:
# ^  = Power 

# (x - mean) ^ 2)
# substituing the values in the above formula 
import math 
sqrt((1 - 5.5) **2 / 10 ) = 1.42

2.025

In [51]:
# std - var 
print(np.var(b1))

8.25


In [52]:
# dot pdoct 
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
print(np.dot(a1, b1))


32
