In [1]:
import numpy as np 

In [ ]:
print("Numpy version is :", np.__version__)

In [ ]:
# Scalar  / Vector / Matrix / Tensor

In [ ]:
# Working with ZEros and ones in numpy array 
zeros = np.zeros((3,4))
print("Zeros Array is :\n", zeros)

In [ ]:
ones = np.ones((2,5))
print("Ones Array is :\n", ones)

In [ ]:
# Reshape command in numpy
array = np.arange(1,13) # n-1
print("Original Array is :\n", array)
print(array.ndim)
print(array.shape)

In [ ]:
array.reshape(3,4)
print("Reshaped Array is :\n", array.reshape(3,4))
print(array.ndim)
print(array.shape)

In [ ]:
array.reshape(4,3)
print("Reshaped Array is :\n", array.reshape(4,3))
print(array.ndim)
print(array.shape)

In [ ]:
array.reshape(2,2,3)
print("Reshaped Array is :\n", array.reshape(2,2,3))
print(array.ndim)
print(array.shape)

In [ ]:
# Important commands 
# 1. arange command 
# 2. linspace command
# 3. random command


In [3]:
new_array = np.arange(12,24) # 24 -12 = 12, 3*4, 4*3, 6*2, 2*6, 2*2*3 , 2*3*2
new_array.reshape(3,4)
print("dim of new_array :", new_array.ndim)
print("shape of new_array :", new_array.shape)

dim of new_array : 1
shape of new_array : (12,)


In [5]:
nag=new_array.reshape(2,2, 3)
print(nag)
print("dim of new_array :", new_array.ndim)
print("shape of new_array :", new_array.shape)

[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
dim of new_array : 1
shape of new_array : (12,)


In [ ]:
new_array.reshape(6,2)
print(new_array)
print("dim of new_array :", new_array.ndim)
print("shape of new_array :", new_array.shape)

In [ ]:
new_array.reshape(2,2,3)
print("The reshaped array is :\n", new_array)
print("dim of new_array :", new_array.ndim) 
print("shape of new_array :", new_array.shape)

In [ ]:
diff_array = np.arange(0,12)
print(diff_array)
#diff_array.reshape(3, 4)
diff_array.reshape(2,2,3)

In [ ]:
diff_array.reshape(2,3,2)

In [ ]:
# 1. arange . 2. linspace 3. random 

In [ ]:
# Linspace : TO create an array with evenly spaced values
# Syntax : np.linspace(start, stop, num, endpoint, retstep, dtype)

linspace_array = np.linspace(0, 10, 5, endpoint=False, retstep=True)

In [7]:
lin_arr_1 = np.linspace(0, 10, 5)
print("The linspace array is :\n", lin_arr_1)

The linspace array is :
 [ 0.   2.5  5.   7.5 10. ]


In [8]:
lin_arr_2 = np.linspace(1, 100, 50)
print("The linspace array is :\n", lin_arr_2)

The linspace array is :
 [  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [9]:
89.89795918 - 87.87755102

2.0204081600000023

In [10]:
53.53061224 - 51.51020408

2.0204081600000023

In [11]:
11.10204082 -9.08163265

2.0204081699999996

In [14]:
# working with random command
random_array = np.random.rand(3, 4)

In [13]:
print("The random array is :\n", random_array)

The random array is :
 [[0.95697739 0.06192872 0.49924689 0.73465043]
 [0.98518754 0.19066807 0.1441374  0.05625298]
 [0.26855453 0.84603311 0.24194622 0.9585974 ]]


In [15]:
print("The random array is :\n", random_array)

The random array is :
 [[0.16808918 0.80007828 0.72254703 0.84449087]
 [0.43407118 0.98048247 0.83655702 0.95007193]
 [0.72376247 0.33681793 0.50603463 0.95506422]]
