In [1]:
print("hi")

hi


In [3]:
import numpy as np

In [5]:
# Working with indexing and slicing 

a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# fetching value 10 from above array 
print(a[3, 1])

10


In [ ]:
# Pandas - Data collection and Data manipulation [ DataFrame and Series ]
# Numpy - to convert data into numbers [ nd.array ]
# MatPlotlib - Visualization 
# Seaborn -  Visualization 
# Scikit- Learn - Machine LEarning Framework [ PNM SS]

In [8]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn 