In [3]:
import numpy as np


In [4]:
first_array = np.array([1, 2, 3, 4, 5])
print(first_array)

[1 2 3 4 5]


In [9]:
second_array_int = np.array([12,13,14], dtype=bool )
print(second_array_int)

[ True  True  True]


In [10]:
# Performing scalar operations
a = np.array([5])
print(a)

[5]


In [12]:
# adding some numbers to scalar (a)
print(a + 10)
print(a * 10)
print(a / 10)
print(a - 10)

[15]
[50]
[0.5]
[-5]


In [ ]:
# when we add scalar+ scalar = ?
# Scalar+ vector = ? 
# scalar * vector = ?
# Dot Product -> Gen AI 

In [16]:
# Vector Operations 
first_vector = np.array([1, 2, 3, 4, 5])
second_vector = np.array([6, 7, 7, 9, 10])
print(first_vector + second_vector)
print(first_vector - second_vector)
print(first_vector * second_vector)
print(first_vector / second_vector)

[ 7  9 10 13 15]
[-5 -5 -4 -5 -5]
[ 6 14 21 36 50]
[0.16666667 0.28571429 0.42857143 0.44444444 0.5       ]


In [18]:
#  array multiplication
first_vector = np.array([1, 2, 3, 4, 5])
second_vector = np.array([6, 7, 8, 9, 10])
result_vector = np.multiply(first_vector, second_vector)
print(result_vector)

[ 6 14 24 36 50]


In [20]:
# Matrix Operations
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
second_matrix = np.array([[7, 8, 9], [10, 11, 12]])
print(first_matrix + second_matrix)
print(first_matrix - second_matrix)
print(first_matrix / second_matrix)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [23]:
# Matrix Multiplication

# Number of column in first matrix = Number of rows in second matrix
first_matrix = np.array([1, 2, 3,]) # (1,3)
second_matrix = np.array([12,13,14]) # (1,3 )


array_multiply = np.multiply(first_matrix, second_matrix)   
print(array_multiply)
# Matrix Multiplication
matrix_multiply = np.matmul(first_matrix, second_matrix)
print(matrix_multiply)


[12 26 42]
80


In [26]:
new_array = np.array([[1,2,3], [4,5,6]])
print(new_array)
print(new_array.shape)
print()
now_array = np.array([[10,20,30], [40,50,60]])
print(now_array)
print(now_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
# performing matrix multiplication (m x n)
matrix_multiply = np.matmul(new_array, now_array)
print(matrix_multiply)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [28]:
# transpose of matrix
tranposed_array = np.transpose(now_array)
print(tranposed_array)
print(tranposed_array.shape)

[[10 40]
 [20 50]
 [30 60]]
(3, 2)


In [29]:
# performing a matrix multiplication
matrix_multiply = np.matmul(new_array, tranposed_array)
print(matrix_multiply)

[[140 320]
 [320 770]]


In [ ]:
# Normal vector / matrix addition, subtraction, division
first_vector = np.array([1, 2, 3])
second_vector = np.array([6, 7, 8])